# Generated by Django 3.1.4 on 2020-12-23 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201222_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='created_by',
            new_name='user',
        ),
    ]
