# Generated by Django 3.1.4 on 2020-12-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201222_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='categoria',
            field=models.CharField(blank=True, choices=[('AL', 'ALIMENTAÇÃO E BEBIDAS'), ('AU', 'AUTOMOTIVA'), ('SA', 'SAUDE'), ('TI', 'TECNOLOGIA DA INFORMAÇÃO'), ('SP', 'SERVIÇOS PESSOAIS'), ('SE', 'SERVIÇOS ESPECIALIZADOS'), ('ED', 'EDUCAÇÃO'), ('CO', 'CONSTRUÇÃO'), ('VE', 'VESTUÁRIO'), ('ET', 'ENTRETENIMENTO')], max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descricao',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
